capp/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo

class RegistrationForm(FlaskForm):
  username = StringField('Username', 
                         validators=[DataRequired(), Length(min=2, max=30)])
  email = StringField('Email',
                      validators=[DataRequired(), Email()])
  password = PasswordField('Password', validators=[DataRequired()])
  confirm_password = PasswordField('Confirm Password',
                      validators=[DataRequired(), EqualTo('password')])                                
  submit = SubmitField('Sign Up')

class LoginForm(FlaskForm):
  email = StringField('Email',
                      validators=[DataRequired(), Email()])
  password = PasswordField('Password', validators=[DataRequired()])
  remember = BooleanField('Remember Me')
  submit = SubmitField('Login') 

capp/__init__.py
from flask import Flask
import os

application = Flask(__name__)

### Code GitHub
# application.config['SECRET_KEY'] = os.environ.get("SECRET_KEY")

### Code Computer
application.config['SECRET_KEY'] = '3oueqkfdfas8ruewqndr8ewrewrouewrere44554'

from capp.home.routes import home
from capp.business.routes import business
from capp.light_talk_app.routes import light_talk_app
from capp.users.routes import users

application.register_blueprint(home)
application.register_blueprint(business)
application.register_blueprint(light_talk_app)
application.register_blueprint(users)


capp/business/__init__.py
#

capp/business/routes.py
from flask import render_template, Blueprint

business=Blueprint('business',__name__)

@business.route('/business')
def business_home():
  return render_template('business.html', title='business')

capp/home/__init__.py
#

capp/home/routes.py
from flask import render_template, Blueprint

home=Blueprint('home',__name__)

@home.route('/')
@home.route('/home')
def home_home():
  return render_template('home.html')

capp/light_talk_app/__init__.py
#

capp/light_talk_app/routes.py
from flask import render_template, Blueprint

light_talk_app=Blueprint('light_talk_app',__name__)

@light_talk_app.route('/light_talk_app')
def light_talk_app_home():
    return render_template('light_talk_app.html', title='light_talk_app')
    

capp/users/__init__.py
#

capp/users/routes.py
from flask import render_template, Blueprint, redirect, flash, url_for
from capp.users.forms import RegistrationForm, LoginForm

users=Blueprint('users',__name__)

@users.route('/register', methods=['GET','POST'])
def register():
  form = RegistrationForm()
  if form.validate_on_submit():
      flash('¡Tu cuenta ha sido creada! ¡Ahora puedes iniciar sesión!', 'success')
      return redirect(url_for('users.login'))
  return render_template('users/register.html', title='register', form=form)

@users.route('/login', methods=['GET','POST'])
def login():
  form = LoginForm()
  if form.validate_on_submit():
    flash('¡Has iniciado sesión! ¡Ahora puedes empezar a utilizar nuestra aplicación Light Talk!', 'success')
    return redirect(url_for('home.home_home'))
  return render_template('users/login.html', title='login', form=form)

capp/templates/business.html
{% extends "layout.html" %}
{% block content %}
    <h1 style="color:blue; text-align: center">Modelo de negocio</h1>

    <p>
        Nuestro modelo de negocio esta basado en dos pilares ....           
    </p>

    <p>
        <strong>Modelo de negocio. A continuación describimos brevemente nuestro modelo de negocio:</strong>
        <ol>
            <li>
                Primer pilar ...
            </li>
            <li>
                Segundo pilar ...
            </li>
        </ol>
    </p>

    <p>Para conocer más sobre nuestro equipo visitar nuestra página principal (<a href="{{ url_for('home.home_home') }}">enlace</a>)

    </p>

    <p>
        <strong>Bibliografía:</strong>
        <ul>
            <li>
                <strong>Artículo 1</strong>: Breve resumen.
            </li>
            <li>
                <strong>Artículo 2</strong>: Breve resumen.
            </li>
        </ul>
    </p>
{% endblock content %}

capp/templates/home.html
{% extends "layout.html" %}
{% block content %}
  <!-- Header -->
  <section class="section_header_home">
    <div class="container">
      <div class="header_home">
        <div class="box">
          {% with messages = get_flashed_messages(with_categories=true) %} {% if
          messages %} {% for category, message in messages %}
          <div class="alert alert-{{ category }}">{{ message }}</div>
          {% endfor %} {% endif %} {% endwith %}
          <script>
            setTimeout(function () {
              var flashes = document.querySelectorAll(".alert");
              flashes.forEach((flash) => flash.remove());
            }, 5000);
          </script>
          <h1 style="font-size: 55px"><span class="text-logo"> Home</span></h1>
          <p style="text-align: left">
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Repellat
            dolores quos asperiores repellendus facilis cum illo aperiam odit
            doloremque nostrum. Totam excepturi labore voluptatibus iusto sapiente
            quisquam consectetur optio magnam voluptates omnis vel officia alias
            distinctio quas laborum reiciendis ratione inventore veniam,
            cupiditate doloribus dolore, eius natus a. Magni inventore
            consequuntur voluptas reprehenderit perferendis! Molestias aspernatur
            rem autem aut temporibus.
          </p>
          <div class="container_buttons_links_header_home">
            <div class="btn">
              <a
                href="#"
                class="btn btn-primary btn-lg mr-2"
                ,
                style="background-color: #007bff"
                >Register</a
              >
            </div>
            <div class="btn">
              <a
                href="#"
                class="btn btn-primary btn-lg mr-2"
                ,
                style="background-color: #007bff"
                >Login</a
              >
            </div>
          </div>
        </div>
        <div class="box">
          <img
            src="{{url_for('static', filename='icons/home.svg')}}"
            width="325"
            height="325"
            alt=""
          />
        </div>
      </div>
    </div>
  </section>

  <!-- Developers -->
  <section class="section_developers">
    <div class="container">
      <div class="developers" style="display: block">
        <h1 style="text-align: center">Our Team</h1>
        <p>
          Nuestro equipo de lingüistas, economistas, educadores y programadores….
          ... Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quia, ut?
          Praesentium quidem sunt perspiciatis doloremque fugiat nesciunt quaerat
          ullam, pariatur iure unde ratione ipsum adipisci repellendus,
          repudiandae hic sit, temporibus molestias corrupti aut soluta sequi!
          Architecto deleniti expedita nisi repudiandae enim eum quas odit facilis
          placeat neque porro, animi incidunt consectetur. Maiores ab saepe
          tempora, iure asperiores beatae suscipit cum ipsum, rerum doloremque
          reprehenderit dolorum debitis, aliquam quasi. Maiores corporis fuga
          quasi nesciunt dolor iste, inventore necessitatibus unde!
        </p>
      </div>

      <div class="developers">
        <div class="box">
          <img
            src="https://randomuser.me/api/portraits/men/10.jpg"
            alt=""
            style="border-radius: 50%; width: 200px"
          />
          <h3>Developer 1</h3>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quia
            repellat omnis? Odit enim hic atque dolorem iste natus inventore
            perspiciatis vitae dolore animi veritatis aut nemo unde similique,
            officia reiciendis ex architecto voluptates soluta ab tempore facilis
            quisquam cum.
          </p>
          <div class="section_container_buttons_developers">
            <a class="btn_developers" href="#" target="_blank">Curriculum</a>
          </div>
        </div>
        <div class="box">
          <img
            src="https://randomuser.me/api/portraits/women/11.jpg"
            alt=""
            style="border-radius: 50%; width: 200px"
          />
          <h3>Developer 2</h3>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quia
            repellat omnis? Odit enim hic atque dolorem iste natus inventore
            perspiciatis vitae dolore animi veritatis aut nemo unde similique,
            officia reiciendis ex architecto voluptates soluta ab tempore facilis
            quisquam cum.
          </p>
          <div class="section_container_buttons_developers">
            <a class="btn_developers" href="#" target="_blank">Curriculum</a>
          </div>
        </div>
        <div class="box">
          <img
            src="https://randomuser.me/api/portraits/men/12.jpg"
            alt=""
            style="border-radius: 50%; width: 200px"
          />
          <h3>Developer 3</h3>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quia
            repellat omnis? Odit enim hic atque dolorem iste natus inventore
            perspiciatis vitae dolore animi veritatis aut nemo unde similique,
            officia reiciendis ex architecto voluptates soluta ab tempore facilis
            quisquam cum.
          </p>
          <div class="section_container_buttons_developers">
            <a class="btn_developers" href="#" target="_blank">Curriculum</a>
          </div>
        </div>
      </div>

      <div class="developers">
        <div class="box2">
          <img
            src="https://randomuser.me/api/portraits/women/12.jpg"
            alt=""
            style="border-radius: 50%; width: 200px"
          />
          <h3>Developer 4</h3>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quia
            repellat omnis? Odit enim hic atque dolorem iste natus inventore
            perspiciatis vitae dolore animi veritatis aut nemo unde similique,
            officia reiciendis ex architecto voluptates soluta ab tempore facilis
            quisquam cum.
          </p>
          <div class="section_container_buttons_developers">
            <a class="btn_developers" href="#" target="_blank">Curriculum</a>
          </div>
        </div>
        <div class="box2">
          <img
            src="https://randomuser.me/api/portraits/women/13.jpg"
            alt=""
            style="border-radius: 50%; width: 200px"
          />
          <h3>Developer 5</h3>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quia
            repellat omnis? Odit enim hic atque dolorem iste natus inventore
            perspiciatis vitae dolore animi veritatis aut nemo unde similique,
            officia reiciendis ex architecto voluptates soluta ab tempore facilis
            quisquam cum.
          </p>
          <div class="section_container_buttons_developers">
            <a class="btn_developers" href="#" target="_blank">Curriculum</a>
          </div>
        </div>
        <div class="box2"></div>
      </div>
    </div>
  </section>

{% endblock content %}


capp/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <!-- Font Awesome code -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
      integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />

    <!--Import the Bootstrap CSS file:-->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
    />

    <!-- CSS code -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='layout.css') }}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='home.css') }}"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='user.css') }}"
    />

    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>home</title>
    {% endif %}
  </head>
  <body>
    <section class="section_light_talk_app_navbar">
      <div class="container">
        <div class="light_talk_app_navbar">
          <h1 class="logo">
            <span class="text-logo"
              ><i class="fa-solid fa-comment-dots"></i> Light Talk</span
            >
            App
          </h1>
          <nav>
            <ul>
              <li>
                <a href="{{url_for('users.register')}}">Register</a>
              </li>
              <li>
                <a href="{{url_for('users.login')}}">Log in</a>
              </li>
              <li>
                <a href="{{url_for('home.home_home')}}">Home</a>
              </li>
              <li>
                <a href="{{url_for('business.business_home')}}">Business</a>
              </li>
              <li>
                <a href="{{url_for('light_talk_app.light_talk_app_home')}}"
                  >Light Talk App</a
                >
              </li>
            </ul>
          </nav>
        </div>
      </div>
    </section>

    {% block content %} {% endblock %}

    <section class="section_footer">
      <div class="container">
        <div class="footer">
          <h1>
            Light Talk App
            <a href="#">
              <i class="fa-solid fa-circle-up" style="color: #568c63"></i>
            </a>
          </h1>
        </div>
      </div>
    </section>

    </body>
</html>

capp/templates/light_talk_app.html
{% extends "layout.html" %}
{% block content %}
    <h1 style="color:blue; text-align: center">Light-Talk-App</h1>

    <p>
        Nuestra app para el aprendizaje del español ...
    </p>    
{% endblock content %}

capp/templates/users/login.html
{% extends "layout.html" %}
{% block content %}

<section class="register_section_css">
  <div class="container">
          <div class="box">

          </div>
          <div class="box">
              {% with messages = get_flashed_messages(with_categories=true) %}
                  {% if messages %}
                      {% for category, message in messages %}
                          <div class="alert alert-{{ category }}">
                              {{ message }}
                          </div> 
                      {% endfor %}
                  {% endif %}
              {% endwith %}
              <script>
                setTimeout(function () {
                  var flashes = document.querySelectorAll('.alert');
                  flashes.forEach((flash) => flash.remove());
                }, 5000);
              </script>
              <form method="POST" action="">
                  {{ form.hidden_tag() }}
                      <fieldset class="form-group">
                          <legend class="border-bottom mb-4">Log In</legend>
                          <div class="form-group">
                              {{ form.email.label(class="form-control-label") }}
                              {% if form.email.errors %}
                                  {{ form.email(class="form-control form-control-lg is-invalid") }}
                                  <div class="invalid-feedback">
                                      {% for error in form.email.errors %}
                                          <span>{{ error }}</span>
                                      {% endfor %}
                                  </div>
                              {% else %}
                                  {{ form.email(class="form-control form-control-lg") }}
                              {% endif %}
                          </div>
                          <div class="form-group">
                              {{ form.password.label(class="form-control-label") }}
                              {% if form.password.errors %}
                                  {{ form.password(class="form-control form-control-lg is-invalid") }}
                                  <div class="invalid-feedback">
                                      {% for error in form.password.errors %}
                                          <span>{{ error }}</span>
                                      {% endfor %}
                                  </div>
                              {% else %}
                                  {{ form.password(class="form-control form-control-lg") }}
                              {% endif %}
                          </div>
                          <div class="form-check">
                              {{ form.remember(class="form-check-input",style="text-align: left;") }}
                              {{ form.remember.label(class="form-check-label",style="text-align: left;") }}
                          </div>
                      </fieldset>
                      </br>
                      <div class="form-group">
                          {{ form.submit(class="btn btn-outline-info") }}
                      </div>
              </form>
              </br>
              <div class="border-top pt-3">
                  <small>
                      Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Register</a>
                  </small>
              </div>

          </div>
          <div class="box">

          </div>
  </div>
</section>

        
{% endblock content %}

capp/templates/users/register.html
{% extends "layout.html" %}
{% block content %}

<section class="register_section_css">
    <div class="container">
            <div class="box">

            </div>
            <div class="box">
                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Join Today</legend>
                        <div class="form-group">
                            {{ form.username.label(class="form-control-label") }}
                            {{ form.username(class="form-control form-control-lg") }}
                        </div>
                        <div class="form-group">
                            {{ form.email.label(class="form-control-label") }}
                            {{ form.email(class="form-control form-control-lg") }}
                        </div>
                        <div class="form-group">
                            {{ form.password.label(class="form-control-label") }}
                            {{ form.password(class="form-control form-control-lg") }}
                        </div>
                        <div class="form-group">
                            {{ form.confirm_password.label(class="form-control-label") }}
                            {{ form.confirm_password(class="form-control form-control-lg") }}
                        </div>
                    </fieldset>
                    </br>
                    <div class="form-group">
                        {{ form.submit(class="btn btn-outline-info") }}
                    </div>
                </form>
                </br>
                <div class="border-top pt-3">
                    <small>
                        Already Have An Account? <a class="ml-5" href="{{ url_for('users.login') }}">Sign In</a>
                    </small>
                </div>

            </div>
            <div class="box">

            </div>
    </div>
</section>

        
{% endblock content %}